#!/usr/bin/env perl
####################################################################################
### script that prints SAML meta-data for a SP using Net::SAML to stdout
### for import at the IDP copy-paste the output into SimpleSAML
#   following the HTTP header, starting with <md:EntityDescriptor>
#
### didn't want to modify GBrowse to give out also the SAML meta-data
### run as 
#   ./samlmeta 2>/dev/null
####################################################################################

use strict;
use warnings;
use CGI qw(:standard);
use CGI::Carp;
use Data::Dumper;
## if zxid is installed in a non-standard location (default: /var/zxid)
## set the VPATH shell variable before running this script, e.g.:
## export VPATH=$HOME/zxid/var/zxid
use Net::SAML;

## Change $url and $idp if not running on localhost
my $url = "https://localhost:80/fgb2/gbrowse/<myorganism>";  # Edit to match the GBrowse db you want to protect
my $idp = "https://localhost:80/simplesaml/saml2/idp/metadata.php";
my $conf = "URL=$url"; ## edit this if zxid is not installed in /var/zxid

my $cf = Net::SAML::new_conf_to_cf($conf);
Net::SAML::url_set($cf, $url);
#Net::SAML::set_opt($cf, 1 ,1); 
my $res = Net::SAML::simple_cf($cf, -1, "o=B", undef, 0x1828); # keep the flags 0x1828 !!! 
my $op = substr($res, 0, 1);

if ($op eq 'L' || $op eq 'C') { print $res."\n";  exit; } # LOCATION (Redir) or CONTENT
die ("unknown result $op");

__END__

